/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controlador;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Funcionario;
import utility.Util;

/**
 *
 * @author hever
 */
public class FrameFuncionario extends javax.swing.JFrame {

    static Controlador control;
    
    Funcionario funcionarioSelecionado;
    
    public FrameFuncionario(Controlador control) {
        initComponents();
        this.control = control;
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public boolean validarCampos(){
        
        Util util = new Util();
        
        String nome = txtNome.getText().toLowerCase();
        String dtEmissao = txtDtEmissao.getText();
        String salario = txtSalario.getText();
        Boolean status = null;
        String validaCampos = "";
        
        if (cmbStatus.getSelectedItem().toString().equals("V")){
            status = true;
        } else if (cmbStatus.getSelectedItem().toString().equals("F")){
            status = false;
        }
       
        if(nome.isEmpty() || dtEmissao.isEmpty() || salario.isEmpty()){            
            validaCampos = validaCampos+"PREENCHA TODOS OS CAMPOS\n";
        }
        
        if (cmbStatus.getSelectedItem().toString().equals("Selecione...")){
            validaCampos = validaCampos+"SELECIONE V OU F NO STATUS\n";    
        }
      
        if (!util.dataValida(dtEmissao)){
            validaCampos = validaCampos+"DATA INVÁLIDA\n";
        }
        
        if (!util.salarioValido(salario)){
            validaCampos = validaCampos+"SALÁRIO INVÁLIDO\n";
        }
        
        if(validaCampos.isEmpty()){
            //JOptionPane.showMessageDialog(null, "TODOS OS CAMPOS VÁLIDOS");
            return true;
        }
        
        JOptionPane.showMessageDialog(null, validaCampos);
        return false;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDtEmissao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        cmbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionário");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAdicionar.setBackground(new java.awt.Color(54, 81, 134));
        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(54, 81, 134));
        jLabel3.setText("FUNCIONÁRIOS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(54, 81, 134));
        jLabel4.setText("Nome:");
        jLabel4.setName("lbNome"); // NOI18N

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(54, 81, 134));
        txtNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNome.setName("txtNome"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 81, 134));
        jLabel5.setText("Data de admissão:");
        jLabel5.setName("lbNome"); // NOI18N

        txtDtEmissao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDtEmissao.setForeground(new java.awt.Color(54, 81, 134));
        try {
            txtDtEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtEmissao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(54, 81, 134));
        jLabel6.setText("Salário:");
        jLabel6.setName("lbNome"); // NOI18N

        txtSalario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSalario.setForeground(new java.awt.Color(54, 81, 134));
        txtSalario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSalario.setName("txtNome"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(54, 81, 134));
        jLabel7.setText("Status");
        jLabel7.setName("lbNome"); // NOI18N

        btnAlterar.setBackground(new java.awt.Color(54, 81, 134));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(54, 81, 134));
        btnDeletar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        tabelaFuncionarios.setForeground(new java.awt.Color(54, 81, 134));
        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Data de Emissão", "Salário", "Status"
            }
        ));
        tabelaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionarios);

        cmbStatus.setForeground(new java.awt.Color(54, 81, 134));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "V", "F" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnAdicionar)
                        .addGap(29, 29, 29)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDtEmissao)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnAlterar)
                    .addComponent(btnDeletar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        if(validarCampos()){
            
            Funcionario f = new Funcionario();
            
            Date data = null;
            
            SimpleDateFormat formatter = new SimpleDateFormat ("dd/MM/yyyy");
            
            try {
                data = formatter.parse(txtDtEmissao.getText());
            } catch (ParseException ex) {
                Logger.getLogger(FrameFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
      
            if (cmbStatus.getSelectedItem().toString().equals("V")){
                f.setStatus(true);
            } else if (cmbStatus.getSelectedItem().toString().equals("F")){
                f.setStatus(false);
            }
            
            f.setNome(txtNome.getText());
            f.setDtEmissao(data);
            f.setSalario(Float.parseFloat(txtSalario.getText()));
            
            try {
                control.cadastrarFuncionario(f);
                txtNome.setText("");
                txtDtEmissao.setText("");
                txtSalario.setText("");
                cmbStatus.setSelectedIndex(0);
                
                control.listarTodosFuncionarios(tabelaFuncionarios);
                
                JOptionPane.showMessageDialog(this, "CADASTRO REALIZADO COM SUCESSO!");
            } 
            catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this, "ERRO DE BANCO DE DADOS " + ex.getMessage() );
            } 
            
            catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Classe não encontrada");
            }   
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        int linha = tabelaFuncionarios.getSelectedRow();
        
        SimpleDateFormat dataString = new SimpleDateFormat ("dd/MM/yyyy");
        
        if(linha >= 0){
            
            funcionarioSelecionado = (Funcionario)tabelaFuncionarios.getValueAt(linha, 1);
            
           if(validarCampos()){

                Date data = null;

                SimpleDateFormat formatter = new SimpleDateFormat ("dd/MM/yyyy");

                try {
                    data = formatter.parse(txtDtEmissao.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(FrameFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (cmbStatus.getSelectedItem().toString().equals("V")){
                    funcionarioSelecionado.setStatus(true);
                } else if (cmbStatus.getSelectedItem().toString().equals("F")){
                    funcionarioSelecionado.setStatus(false);
                }

                funcionarioSelecionado.setNome(txtNome.getText());
                funcionarioSelecionado.setDtEmissao(data);
                funcionarioSelecionado.setSalario(Float.parseFloat(txtSalario.getText()));

                try {
                    control.alterarFuncionario(funcionarioSelecionado);
                    txtNome.setText("");
                    txtDtEmissao.setText("");
                    txtSalario.setText("");
                    cmbStatus.setSelectedIndex(0);
                    
                    control.listarTodosFuncionarios(tabelaFuncionarios);

                    JOptionPane.showMessageDialog(this, "FUNCIONARIO ALTERADO COM SUCESSO!");
                } 
                catch (SQLException ex) {
                     JOptionPane.showMessageDialog(this, "ERRO DE BANCO DE DADOS " + ex.getMessage() );
                } 

                catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Classe não encontrada");
                }   
            }
            
            }
        
            else{
                    JOptionPane.showMessageDialog(this, "Para alterar, selecione um funcionario na tabela");
            }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        
        int linha = tabelaFuncionarios.getSelectedRow();
        
        SimpleDateFormat dataString = new SimpleDateFormat ("dd/MM/yyyy");
        
        if(linha >= 0){
            
            funcionarioSelecionado = (Funcionario)tabelaFuncionarios.getValueAt(linha, 1);
            
            if ( JOptionPane.showConfirmDialog(this, "Excluir Funcionário ? " +
                        funcionarioSelecionado.getNome(), "Confirmar", JOptionPane.YES_NO_OPTION  ) == JOptionPane.OK_OPTION  ) {
            
                try {
                        control.deletarFuncionario(funcionarioSelecionado);
                        txtNome.setText("");
                        txtDtEmissao.setText("");
                        txtSalario.setText("");
                        cmbStatus.setSelectedIndex(0);

                        control.listarTodosFuncionarios(tabelaFuncionarios);

                        JOptionPane.showMessageDialog(this, "FUNCIONARIO EXCLUIDO COM SUCESSO!");
                    } 
                    catch (SQLException ex) {
                         JOptionPane.showMessageDialog(this, "ERRO DE BANCO DE DADOS " + ex.getMessage() );
                    } 

                    catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Classe não encontrada");
                    } 
            
              }  
            }
            else{
                JOptionPane.showMessageDialog(this, "Para excluir, selecione um funcionario na tabela");
            }
        
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            control.listarTodosFuncionarios(tabelaFuncionarios);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Classe não encontrada");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERRO DE BANCO DE DADOS " + ex.getMessage() );
        }
    }//GEN-LAST:event_formComponentShown

    private void tabelaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionariosMouseClicked
        
        int linha = tabelaFuncionarios.getSelectedRow();
        
        SimpleDateFormat dataString = new SimpleDateFormat ("dd/MM/yyyy");
        
        if(linha >= 0){
            funcionarioSelecionado = (Funcionario)tabelaFuncionarios.getValueAt(linha, 1);
            
            txtNome.setText(funcionarioSelecionado.getNome());
            txtSalario.setText(String.valueOf(funcionarioSelecionado.getSalario()));
            txtDtEmissao.setText(dataString.format(funcionarioSelecionado.getDtEmissao()));
            
            if(funcionarioSelecionado.getStatus()){
                cmbStatus.setSelectedIndex(1);
            } else{
                cmbStatus.setSelectedIndex(2);
            }
            
        }
        
    }//GEN-LAST:event_tabelaFuncionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFuncionario(control).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JFormattedTextField txtDtEmissao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
